import classes from "./Grid.module.css";

const arr = [
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
  { text: 1 },
];

const Grid = () => {
  return (
    <div className={classes.grid}>
      {arr.map((item, index) => {
        return (
          <div key={index} className={classes.ico}>
            {item.text}
          </div>
        );
      })}
    </div>
  );
};

export default Grid;
